# Generated by Django 5.1.7 on 2025-03-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='custmor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.custmor'),
        ),
        migrations.AddField(
            model_name='product',
            name='custmor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.custmor'),
            preserve_default=False,
        ),
    ]
