# Generated by Django 5.1.7 on 2025-03-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_custmor_cart_custmor_product_custmor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custmor',
            name='created_at',
        ),
        migrations.AddField(
            model_name='custmor',
            name='addresses',
            field=models.JSONField(default=list),
        ),
    ]
