# Generated by Django 5.1.7 on 2025-03-17 01:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_rename_custmor_design_customer'),
        ('store', '0003_remove_custmor_created_at_custmor_addresses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custmor',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='custmor',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='custmor',
            new_name='customer',
        ),
    ]
