# Generated by Django 5.1.7 on 2025-03-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_custmor_customer_rename_custmor_cart_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
