# Generated by Django 5.1.7 on 2025-03-17 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_total_amount_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='store.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.cart'),
        ),
    ]
