# Generated by Django 5.1.7 on 2025-04-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
