# Generated by Django 5.1.7 on 2025-04-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='unit_price',
        ),
    ]
