# Generated by Django 5.1.7 on 2025-03-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='custmor',
            new_name='customer',
        ),
    ]
