# Generated by Django 5.1.7 on 2025-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_rename_custmor_design_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='design_uploads/'),
        ),
        migrations.AddField(
            model_name='design',
            name='file_type',
            field=models.CharField(blank=True, choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('svg', 'SVG')], max_length=10, null=True),
        ),
    ]
