# Generated by Django 5.1.7 on 2025-04-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_design_design_file_design_file_type'),
        ('designs', '0004_remove_template_name'),
    ]

    operations = [
    ]
